[build]
  command = "npm run build"
  publish = "public"
  functions = "netlify-functions-build"

[build.environment]
  NODE_VERSION = "18.9.0"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

[dev]
  functions = "netlify-functions"
  publish = "public"
