[build]
  command = "npm run build"
  publish = "public"
  functions = "netlify-functions-build"

[build.environment]
  NODE_VERSION = "18.9.0"

[dev]
  functions = "netlify-functions"
  publish = "public"
